name: Playwright VPS Test
on: 
  push:
  workflow_dispatch:
    inputs:
      target_url:                     
        description: 'URL to scrape'
        required: true
        default: 'https://example.com'

jobs:
  playwright-runner:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Playwright
        run: |
          source ~/venv-playwright/bin/activate
          # Pass the input from GitHub to the Python script as an argument
          python3 playground-plr.py "${{ github.event.inputs.target_url }}"